version: '3.3'

services:
  post_db:
    image: mongo:${MONGODB_IMG_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      - reddit

  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_IMG_VERSION}
    ports:
      - 9292:${UI_EXTERNAL_PORT}/tcp
    networks:
      - reddit

  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_IMG_VERSION}
    networks:
    - reddit

  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_IMG_VERSION}
    networks:
    - reddit

volumes:
  post_db:

networks:
  reddit: