version: '3.3'

services:
  prometheus:
    image: ${USERNAME}/prometheus:latest
    ports:
      - 9090:9090/tcp
    networks:
      - back_net
      - front_net

  post_db:
    image: mongo:${MONGODB_IMG_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      - back_net

  ui:
    # build: ./ui
    image: ${USERNAME}/ui:${UI_IMG_VERSION}
    ports:
      - 9292:${UI_EXTERNAL_PORT}/tcp
    networks:
      - front_net

  post:
    # build: ./post-py
    image: ${USERNAME}/post:${POST_IMG_VERSION}
    networks:
      - back_net
      - front_net

  comment:
    # build: ./comment
    image: ${USERNAME}/comment:${COMMENT_IMG_VERSION}
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  back_net:
    ipam:
      config:
        - subnet: 10.0.2.0/24
  front_net:
    ipam:
      config:
        - subnet: 10.0.1.0/24